### PR TITLE
feat!: upgrade Prettier to v3.0.0

### PR DESCRIPTION
**Pull request by p-kuen**
This requires to use prettier v3.0.0, so there should be a new major version for this package to.

### CODE REVIEW

**Review by sodatea — APPROVED** [review]
Thanks!

**Comment by gegoune** [comment]
@sodatea Thanks for looking into it; when can we expect new release?

**Comment by sodatea** [comment]
In a day.
But please don't do this again. It's kinda rude and puts undue pressure on maintainers.

I was just looking into documentation and changelogs to see if I was missing anything when I got the email notification.
Now I'm interrupted and in a bad mood.

**Comment by gegoune** [comment]
Please accept my apologies, didn't intend to put any pressure at all. I am not familiar with that project and its release cycle - was just curious. Appreciate your work on it and don't mind waiting as long as needed. Hope you get back in good mood soon! :)

**Pull request merged**
